server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: pass1234
    url: jdbc:mysql://localhost:3306/flockit
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
